[project]
name = "pato-gui"
version = "4.0.1"
description = "Paulissoft Application Tools for Oracle (PATO) GUI."
# authors = ["Gert-Jan Paulissen <paulissoft@gmail.com>"]
# license = "MIT"
readme = "README.md"
homepage = "https://paulissoft.github.io/pato-gui"
repository = "https://github.com/paulissoft/pato-gui"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[dependencies]
python = ">=3.8.1,<3.13"
wxpython = ">=4.1.0"
poetry = ">=1.8.3,<2"
pip = ">=24.2,<25"
