# This is a valid pyproject.toml without dependencies only used to speed up Dockerfile builds.
# There must be a [tool.poetry] section with some fields otherwise you may get this kind of error:
#
#   The Poetry configuration is invalid:
#   - The fields ['authors', 'description', 'name', 'version'] are required in package mode.
#
[tool.poetry]
name = "pato-gui"
version = "4.0.1"
description = "Paulissoft Application Tools for Oracle (PATO) GUI."
authors = ["Gert-Jan Paulissen <paulissoft@gmail.com>"]
license = "MIT"
readme = ["README.md", "CHANGELOG.md"]
packages = [{include = "pato_gui", from = "src"}]
